jenkins:
  systemMessage: "Jenkins configuracion inicial"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  clouds:
    - docker:
        name: 'dockercito'
        dockerApi:
          dockerHost:
            uri: "tcp://dind:2375"
        exposeDockerHost: true
        templates:
          - name: "terraform-agent"
            labelString: "terraform"
            dockerTemplateBase:
              image: "sebastiangilian/agent:latest"
              tty: true
              privileged: false
            connector:
              attach: {}
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "aws-access-key"
              secret: "${AWS_ACCESS_KEY_ID}"
              description: "AWS Access Key ID (Secret Text)"
          
          - string:
              scope: GLOBAL
              id: "aws-secret-key"
              secret: "${AWS_SECRET_ACCESS_KEY}"
              description: "AWS Secret Access Key (Secret Text)"


jobs:
  - script: |
      pipelineJob('aproil-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/RAgredaIpar/aproil-backend.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }